name: Backend Lint

on:
  pull_request:
    branches:
      - master

jobs:
  run-linting:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install backend dependencies
        working-directory: ./backend
        run: yarn install
      
      - name: Generate Prisma Types
        run: yarn db:generate
      
      - name: Run eslint
        run: yarn lint

      # - name: Run linters
      #   uses: wearerequired/lint-action@v2
      #   with:
      #     eslint: true
      #     prettier: true