name: Build

on:
  pull_request:
    branches:
      - master

jobs:
  Eslint:
    name: Eslint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [backend, frontend]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install ${{matrix.directory}} dependencies
        run: cd ${{matrix.directory}} && yarn install
      
      - name: Build ${{matrix.directory}}
        run: cd ${{matrix.directory}} && yarn build