name: Deploy Changes

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Connect to droplet
        run: doctl compute ssh ${{ secrets.DIGITALOCEAN_DROPLET_ID }}
      - name: Run deploy script
        run: ./projects/wearit/scripts/deploy.sh

      