name: Backend Lint

on:
  pull_request:
    branches:
      - master

jobs:
  run-linting:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install backend dependencies
        run: cd backend && yarn install
      
      - name: Generate Prisma Types
        run: cd backend && yarn db:generate
      
      - name: Run eslint
        run: cd backend && yarn lint